---
title: "Plot_Mean_Turbidity_Globally_Final"
author: "SS"
date: "November 30, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

#This reads in the raster of mean turbidity globally and plots it, creating Figure 1.

```{r load libraries}
library(raster)
library(rgdal)
library(GISTools)
library(ncdf4)
library(fields)
```

home<-"C:/Users/Shannon/Desktop/Ecoregions/turbidity/Final"
setwd(home)
mean_turbidity_raster<-raster("turbidity_raster_mean.nc")

```{r plotmap_function}
plot.map<- function(database,center,transf=T,...){
  Obj <- map(database,...,plot=F)
  coord <- cbind(Obj[[1]],Obj[[2]])
  newproj <- "+proj=merc +lon_0=150 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" #utm
  nextproj<-"+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0" #latlong
  # split up the coordinates
  id <- rle(!is.na(coord[,1]))
  id <- matrix(c(1,cumsum(id$lengths)),ncol=2,byrow=T)
  polygons <- apply(id,1,function(i){coord[i[1]:i[2],]})
  
  # split up polygons that differ too much
  polygons <- lapply(polygons,function(x){
    x[,1] <- x[,1] + center
    x[,1] <- ifelse(x[,1]>180,x[,1]-360,x[,1])
    if(sum(diff(x[,1])>300,na.rm=T) >0){
      id <- x[,1] < 0
      x <- rbind(x[id,],c(NA,NA),x[!id,])
    }
    x
  })
  # reconstruct the object
  polygons <- do.call(rbind,polygons)
  
  
  colnames(polygons)<-c("x",'y')
  polygons<-as.data.frame(polygons)
  z<-complete.cases(polygons)
  p<-z
  z<-cbind(z,z)
  polygons<-polygons[complete.cases(polygons),]
  coordinates(polygons)<-~x+y
  proj4string(polygons)<-CRS(nextproj)
  if(transf==T){ polygons<-spTransform(polygons,CRS(newproj))}
  
  z[p==F,]<-c(NA,NA)
  z[which(p==T),]<-coordinates(polygons)
  Obj[[1]] <- z[,1]
  Obj[[2]] <- z[,2]
  
  map(Obj,...)
}
```

mean_turbidity_raster<-projectRaster(mean_turbidity_raster, crs="+proj=merc +lon_0=150 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")

#some values are outliers and it makes the plot lose some of the fine details. We set the scale from 0 to .2, and everything greater than .2 (only a few outliers) get plotted the same color as .2. We also specify this in the legend. 
mean_turbidity_raster[mean_turbidity_raster>0.2]<-.2

colramp<-colorRampPalette(c('blue','turquoise2','green','yellow','orange','brown'))(50)

```{r make Figure1}
tiff(file=file.path(home,'Figure1.tif'),height=800,width=3000,res=300)
par(mgp=c(0.5,0.6,0), mar=c(0,0,0,0))
plot(mean_turbidity_raster, xlim=c(111319.4*-180,111319.4*180), ylim=c(111319.4*-48, 111319.4*57), legend=FALSE, col=colramp)
box()
axis(1,at=c(-10018754.17,3339584.724,16697920),lab=c('60°','180°','-60° '),las=1,tcl=0.35,mgp=c(-1,-1.3,0))
axis(2, at=c(23*111319.4666666667,0,-23*111319.4666666667),labels=c('23°','0°','-23°'),las=3,tcl=0.35,mgp=c(-2,-1.3,0),hadj=.4)
axis(3,at=c(-10018754.17,3339584.724,16697920),lab=c('','',''),las=1,tcl=0.35,mgp=c(-1,-1.3,0))
axis(4, at=c(23*111319.4666666667,0,-23*111319.4666666667),labels=c('','',''),las=2,tcl=0.35,mgp=c(-1,-0.6,0),hadj=0)
windowsFonts(A=windowsFont('Arial Unicode MS'))
text(-7868896,-2922012,'Indian Ocean',cex=1.0, family='A')
text(9438742,487176,'Pacific Ocean',cex=1.0, family='A')
text(x=(-16654136+111319.4*305), y=1615153*2.2,'Atlantic Ocean',cex=1.0, family='A')
north.arrow(x=(-16654136+111319.4*220), y=1615153*3, len=(111319.4*2), lab="N", cex=.7)
scalebar(d=111319.4*36, xy=c((-16654136+111319.4*-27), (1615153*-2.9)), type='bar', divs=4, below="kilometers", label=c("0", "", "4000"))
#legend
mapcol  <- colorRampPalette(c(colramp))
plotrix::color.legend(6184797,-28*111319.4666666667,14184797,-23.5*111319.4666666667,legend=c("0",">0.2"),rect.col=mapcol(50),cex=1)
text(((14184797)-(6184797))/2+(6184797),-17*111319.4666666667,expression("K"[d]*"490"))
plot.map("world", center=0 ,bg="#00000000",ylim=c(-90,90),fill=FALSE,add=T,xlab='longitude',ylab='latitude') #center is still 0
dev.off()
```